# Generated by Django 6.1.1 on 2026-09-18 22:57

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='WeeklyReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.PositiveIntegerField(verbose_name='Yıl')),
                ('week', models.PositiveIntegerField(verbose_name='Hafta')),
                ('gross_revenue', models.DecimalField(decimal_places=2, default=0, max_digits=15, verbose_name='Haftalık Brüt Ciro')),
                ('gross_sales_quantity', models.PositiveIntegerField(default=0, verbose_name='Brüt Satış Adedi')),
                ('average_commission_rate', models.DecimalField(decimal_places=4, default=0, max_digits=6, verbose_name='Ort. Komisyon Oranı')),
                ('unavailable_product_count', models.PositiveIntegerField(default=0, verbose_name='Tedarik Edilemeyen Ürün Adedi')),
                ('delivery_time', models.DecimalField(decimal_places=2, default=0, max_digits=8, verbose_name='Kargoya Teslim Süresi')),
                ('active_product_stock', models.PositiveIntegerField(default=0, verbose_name='Aktif Ürün Stok Adedi')),
                ('active_model_count', models.PositiveIntegerField(default=0, verbose_name='Aktif Renk Bazlı Model Adedi')),
                ('total_views', models.PositiveIntegerField(default=0, verbose_name='Toplam Görüntülenme Sayısı')),
                ('seller_views', models.PositiveIntegerField(default=0, verbose_name='Satıcı Görüntüleme Sayısı')),
                ('add_to_cart_count', models.PositiveIntegerField(default=0, verbose_name='Sepete Eklenme Sayısı')),
                ('gross_order_count', models.PositiveIntegerField(default=0, verbose_name='Brüt Sipariş Adedi')),
                ('follower_count', models.PositiveIntegerField(default=0, verbose_name='Mağaza Takipçi Sayısı')),
                ('product_ad_revenue', models.DecimalField(decimal_places=2, default=0, max_digits=15, verbose_name='Ürün Reklam Cirosu')),
                ('product_ad_spend', models.DecimalField(decimal_places=2, default=0, max_digits=15, verbose_name='Ürün Reklam Harcaması')),
                ('product_ad_impressions', models.PositiveIntegerField(default=0, verbose_name='Ürün Reklam Görüntülenme')),
                ('product_ad_clicks', models.PositiveIntegerField(default=0, verbose_name='Ürün Reklam Tıklanma')),
                ('meta_ad_revenue', models.DecimalField(decimal_places=2, default=0, max_digits=15, verbose_name='Meta Reklam Cirosu')),
                ('meta_ad_spend', models.DecimalField(decimal_places=2, default=0, max_digits=15, verbose_name='Meta Reklam Harcaması')),
                ('meta_ad_impressions', models.PositiveIntegerField(default=0, verbose_name='Meta Reklam Görüntülenme')),
                ('meta_ad_clicks', models.PositiveIntegerField(default=0, verbose_name='Meta Reklam Tıklanma')),
                ('cancellation_count', models.PositiveIntegerField(default=0, verbose_name='İptal Adedi')),
                ('cancellation_lost_revenue', models.DecimalField(decimal_places=2, default=0, max_digits=15, verbose_name='İptal Kaybedilen Ciro')),
                ('return_count', models.PositiveIntegerField(blank=True, null=True, verbose_name='İade Adedi')),
                ('return_lost_revenue', models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True, verbose_name='İade Kaybedilen Ciro')),
                ('commission_stock_count', models.PositiveIntegerField(default=0, verbose_name='Komisyon Giren Stok Adedi')),
                ('three_star_stock_count', models.PositiveIntegerField(default=0, verbose_name='3 Yıldız Giren Stok Adedi')),
                ('two_star_stock_count', models.PositiveIntegerField(default=0, verbose_name='2 Yıldız Giren Stok Adedi')),
                ('one_star_stock_count', models.PositiveIntegerField(default=0, verbose_name='1 Yıldız Giren Stok Adedi')),
                ('campaign_stock_count', models.PositiveIntegerField(default=0, verbose_name='Kampanya Giren Stok Adedi')),
                ('commission_model_count', models.PositiveIntegerField(default=0, verbose_name='Komisyon Giren Model Sayısı')),
                ('three_star_model_count', models.PositiveIntegerField(default=0, verbose_name='3 Yıldız Giren Model Sayısı')),
                ('two_star_model_count', models.PositiveIntegerField(default=0, verbose_name='2 Yıldız Giren Model Sayısı')),
                ('one_star_model_count', models.PositiveIntegerField(default=0, verbose_name='1 Yıldız Giren Model Sayısı')),
                ('campaign_model_count', models.PositiveIntegerField(default=0, verbose_name='Kampanya Giren Model Sayısı')),
                ('commission_revenue', models.DecimalField(decimal_places=2, default=0, max_digits=15, verbose_name='Komisyon Ciro Getirisi')),
                ('three_star_revenue', models.DecimalField(decimal_places=2, default=0, max_digits=15, verbose_name='Yıldız Ciro Getirisi')),
                ('campaign_revenue', models.DecimalField(decimal_places=2, default=0, max_digits=15, verbose_name='Kampanya Ciro Getirisi')),
                ('coupon_stock_count', models.PositiveIntegerField(default=0, verbose_name='Üründen Kazan Kupon Stok Adedi')),
                ('coupon_model_count', models.PositiveIntegerField(default=0, verbose_name='Üründen Kazan Kupon Model Sayısı')),
                ('coupon_revenue', models.DecimalField(decimal_places=2, default=0, max_digits=15, verbose_name='Kupon Getirisi')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Haftalık Rapor',
                'verbose_name_plural': 'Haftalık Raporlar',
                'ordering': ['-year', '-week'],
                'constraints': [models.UniqueConstraint(fields=('year', 'week'), name='unique_year_week')],
            },
        ),
    ]
